### ISSUE TITLE
Passing credentials to Gradle 

### ISSUE THREAD

**Issue by buehlerjochen** [mikepenz/gradle-dependency-submission#278]
Hi, thank you for the interesting plugin. I wanted to check it out, but I can not get my build to run.

The problem is that the action tries to execute Gradle, but does not have the credentials for our internal repositories and I do not know how to supply them through the action.

What we do in the regular build:

```
    - name: Gradle build
      run: ./gradlew -i --stacktrace --no-daemon build -PartifactoryUserName=${{ secrets.ARTIFACTORY_USERNAME }} -PartifactoryUserPassword=${{ secrets.ARTIFACTORY_APIKEY }}
```

This creates the properties `artifactoryUserName` and `artifactoryUserPassword` on the project, which can be used just like ordinary properties.

For example the `settings.gradle.kts`:
```
pluginManagement {
    repositories {
        gradlePluginPortal() // Include public Gradle plugin portal
        mavenLocal()
        mavenCentral()

        val artifactoryUserName: String by settings
        val artifactoryUserPassword: String by settings

        maven(url = "https://<internalRepository>/artifactory/repoX/") {
            credentials {
                username = bdcArtifactoryUserName
                password = bdcArtifactoryUserPassword
            }
        }
    }
}

rootProject.name = "custom"
```

But this fails with the error that Gradle can not resolve the properties when running 

```
    - name: Collect project dependencies
      uses: mikepenz/gradle-dependency-submission@v0.8.6
      with:
        gradle-build-module: |-
          :
        gradle-build-configuration: "compileClasspath"
```
```
FAILURE: Build failed with an exception.
  
  * Where:
  Settings file '/home/build/ghactions/xxx/settings.gradle.kts' line: [22]
  
  * What went wrong:
  Cannot get non-null property 'artifactoryUserName' on settings 'custom-gradle-plugin' as it does not exist
```

Is there a way to pass flags and properties to Gradle as one would on the command line?

Kind regards,
Jochen
