### ISSUE TITLE
Dependabot recognises submitted dependencies as Maven

### ISSUE THREAD

**Issue by n0rdy** [mikepenz/gradle-dependency-submission#360]
Hello there!

First of all, thanks a lot for the great project: it was really easy to set things up and get it up and running in no time - a great job! 

After the dependencies had been submitted, several security vulnerabilities were spotted by the Dependabot, and it tried to create a PR with the fix; however, this failed with
![CleanShot 2023-09-15 at 10 29 23](https://github.com/mikepenz/gradle-dependency-submission/assets/24653053/99532b73-f530-41bd-9a18-82688621adda)

I'm trying to figure it whether this issue is related to the `gradle-dependency-submission` action flow. Can you help me with this, please?

**Some context:**
Dependency submission action configs:
```
name: Gradle Dependency Submission
on:
  push:
    branches:
      - main

jobs:
  gradle-action-detection:
    runs-on: [ ubuntu-latest ]
    # The Dependency Submission API requires write permission
    permissions:
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: corretto

      - name: Submit Gradle Dependencies
        uses: mikepenz/gradle-dependency-submission@v0.9.0
        with:
          gradle-project-path: "."
          gradle-build-module: |-
            :
          gradle-build-configuration: |-
            compileClasspath
```

Dependabot configs:
```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    # Enables only security updates, but disables version updates:
    # https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
    open-pull-requests-limit: 0
```

The submitted dependencies under the `Insights -> Dependency graph` section look fine: they are all within the `Snapshot dependencies associated with build.gradle.kts` section - so no Maven is mentioned here.

Is this something known for the `gradle-dependency-submission` action behaviour? I suspect maybe it has smth to do with the fact that most of them are transitive dependencies (not all, though).

Thanks, and have a great day!
